test_that("synthetic defaults match Study Manager conventions", {
  root <- tempfile("carwatch-defaults-")
  generate_synthetic_study_data(root, n_participants = 1, validate = FALSE)
  folders <- stats::setNames(file.path(root, "logs", "VP_01"), "VP_01")
  schedule <- extract_registration_schedule(read_raw_logs_from_participant_dirs(folders))
  expect_identical(unique(schedule$study_name), "Study1")
  expect_identical(unique(schedule$scheduled_sample), paste0("S", 1:4))
  expect_identical(unique(schedule$day), paste0("D", 1:4))
})

test_that("synthetic issue and compliance ratios are exact and patchable", {
  root <- tempfile("carwatch-counts-")
  generate_synthetic_study_data(root, n_participants = 2, random_state = 11, non_compliant_sample_ratio = 5 / 32, missing_awakening_time_ratio = 2 / 8, missing_sampling_time_ratio = 3 / 32)
  folders <- stats::setNames(file.path(root, "logs", c("VP_01", "VP_02")), c("VP_01", "VP_02"))
  raw <- read_raw_logs_from_participant_dirs(folders)
  advisory <- suppressWarnings(convert_raw_logs(raw, errors = "warn", create_report = TRUE))
  counts <- table(advisory$report$issues$code)
  expect_identical(unname(counts["missing_awakening_time"]), 2L)
  expect_identical(unname(counts["missing_scheduled_sample_event"]), 3L)
  final <- convert_raw_logs(raw, errors = "raise", issue_decisions = read_conversion_report(file.path(root, "issue_decisions.csv")), manual_diary = read_manual_diary(file.path(root, "manual_diary.csv")))
  samples <- as_sample_events(final)
  expect_identical(sum(samples$sample_compliant %in% FALSE), 5L)
  expect_identical(sum(samples$sampling_time_source == "manual_diary", na.rm = TRUE), 3L)
})

test_that("synthetic aliases and multiple registrations preserve opaque IDs", {
  root <- tempfile("carwatch-registrations-")
  generate_synthetic_study_data(root, n_participants = 1, validate = FALSE, study_config = list(N = "QR example", SS = "T0", T = c(0, 30), A = "12:00", E = 1, FD = 0, FM = 1, registrations = list(list(N = "Study1", D = 1, registration_date = "2026-05-01", saliva_ids = c("baseline", "rise", "noon")), list(N = "Study2", D = 1, registration_date = "2026-05-08", saliva_ids = c("tube-x", "tube-y", "tube-z")))))
  folder <- stats::setNames(file.path(root, "logs", "VP_01"), "VP_01")
  schedule <- extract_registration_schedule(read_raw_logs_from_participant_dirs(folder))
  expect_identical(unique(schedule$study_name), c("Study1", "Study2"))
  expect_identical(split(schedule$scheduled_sample, schedule$registration), list(`1` = c("baseline", "rise", "noon"), `2` = c("tube-x", "tube-y", "tube-z")))
})

test_that("decoded Study Manager QR configurations are accepted", {
  root <- tempfile("carwatch-qr-")
  generate_synthetic_study_data(root, validate = FALSE, study_config = "CARWATCH;N:QRExample;D:2;NP:1;SS:S1;T:0,30,15,15;A:;E:0;FD:1;FM:0;V:1.0.0")
  folder <- stats::setNames(file.path(root, "logs", "VP_01"), "VP_01")
  schedule <- extract_registration_schedule(read_raw_logs_from_participant_dirs(folder))
  expect_identical(unique(schedule$day), c("D1", "D2"))
  expect_identical(unique(schedule$scheduled_sample), paste0("S", 1:4))
})

test_that("synthetic cortisol, reproducibility, and overwrite contracts hold", {
  first <- tempfile("carwatch-first-"); second <- tempfile("carwatch-second-")
  generate_synthetic_study_data(first, n_participants = 1, random_state = 42, create_cortisol_data = TRUE)
  generate_synthetic_study_data(second, n_participants = 1, random_state = 42, create_cortisol_data = TRUE)
  expect_identical(readLines(file.path(first, "manual_diary.csv")), readLines(file.path(second, "manual_diary.csv")))
  expect_identical(readLines(file.path(first, "cortisol.csv")), readLines(file.path(second, "cortisol.csv")))
  cortisol <- readr::read_csv(file.path(first, "cortisol.csv"), show_col_types = FALSE)
  profile <- dplyr::summarise(dplyr::group_by(cortisol, .data$sample_position), cortisol = mean(.data$cortisol), .groups = "drop")
  expect_gt(profile$cortisol[[3]], profile$cortisol[[2]])
  expect_gt(profile$cortisol[[2]], profile$cortisol[[1]])
  expect_lt(profile$cortisol[[4]], profile$cortisol[[3]])
  expect_error(generate_synthetic_study_data(first, n_participants = 1), "overwrite")
  expect_silent(generate_synthetic_study_data(first, n_participants = 1, overwrite = TRUE, validate = FALSE))
  expect_error(generate_synthetic_study_data(tempfile("invalid-"), study_config = list(non_compliant_sample_count = 1)), "function parameters")
})
